name: Account Service CI/CD

on:
  push:         { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  pipeline:
    uses: my-banking-app/ci-templates/.github/workflows/java-ms-ci-cd.yml@v1.0.0
    with:
      service_name:      account-service
      sonar_project_key: my-banking-app_bank-ms-account-service
      docker_image:      ${{ secrets.DOCKER_USERNAME }}/account-service:prod
      container_port:    8083
    secrets: inherit
